name: CD - Deploy con Git Pull

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectarse al servidor y desplegar
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}   # Clave privada para conectar al servidor (runner -> servidor)
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -euo pipefail

            # Path de tu proyecto en el servidor
            cd ~/lemp-sites/lucas_perez

            # Forzar a que este repo use solo la clave correcta hacia GitHub
            git config core.sshCommand "ssh -i $HOME/.ssh/id_deploy -o IdentitiesOnly=yes"

            # Asegurar que el remoto sea el correcto
            git remote set-url origin git@github.com:LucasJavierPerez/devops_serv.git

            # Actualizar el código
            git fetch origin
            git checkout main
            git pull --ff-only origin main
