name: Deploy

on:
  workflow_run:
    workflows: [ "CI" ]
    types: [ "completed" ]
    branches: [ "main" ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Conectarse por SSH y hacer git pull
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd ~/lemp-sites/nombre_apellido
            git pull
            # Opcional según tu proyecto:
            # npm ci --omit=dev
            # pm2 reload app || true
            # systemctl --user restart tu-servicio || true
