name: Deploy Production

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Test SSH connectivity
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" \
              -o StrictHostKeyChecking=no \
              "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" 'echo OK desde GitHub Actions'

      - name: Deploy to PRODUCTION
        run: |
          rsync -az --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "node_modules" \
            -e "ssh -p ${{ secrets.SSH_PORT }} -o IdentitiesOnly=yes" \
            ./ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/lemp-sites/${{ secrets.SITE_DIR }}/production/"
