name: Deploy Staging
on:
  push:
    branches: [ "develop" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
      - name: Ensure remote dir exists (staging)
        run: ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "mkdir -p ~/lemp-sites/${{ secrets.SITE_DIR }}/staging"
    
      - name: Deploy to STAGING
        run: rsync -az --delete --exclude ".git" --exclude ".github" --exclude "node_modules" \
          -e "ssh -p ${{ secrets.SSH_PORT }}" \
          ./ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/lemp-sites/${{ secrets.SITE_DIR }}/staging/"
    
      - name: Write deploy log (staging)
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "echo 'Deploy a STAGING en $(date) - commit $GITHUB_SHA' >> ~/lemp-sites/${{ secrets.SITE_DIR }}/staging/deploy.log"
